2021-08-29 12:28:30,120 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:43]
2021-08-29 12:49:35,318 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:43]
2021-08-29 12:53:38,244 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:43]
2021-08-29 12:58:44,331 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:43]
2021-08-29 14:08:57,773 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:45]
2021-08-29 14:31:51,023 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:45]
2021-08-29 14:32:06,619 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:45]
2021-08-29 14:32:19,551 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:45]
2021-08-29 14:32:28,402 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:45]
2021-08-30 20:03:52,978 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
2021-08-30 20:05:49,654 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
2021-08-30 20:10:21,796 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
2021-08-30 20:10:36,977 ERROR: Exception on /reset_password_request [POST] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/main/PycharmProjects/microblog/app/routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 24, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 20, in send_email
    sendemail(msg)
TypeError: sendemail() missing 1 required positional argument: 'msg'
2021-08-30 20:12:04,835 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
2021-08-30 20:12:37,087 ERROR: Exception on /reset_password_request [POST] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/main/PycharmProjects/microblog/app/routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 24, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 20, in send_email
    sendemail(msg)
TypeError: sendemail() missing 1 required positional argument: 'msg'
2021-08-30 20:13:19,333 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
2021-08-30 20:13:39,504 ERROR: Exception on /reset_password_request [POST] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/main/PycharmProjects/microblog/app/routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 24, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 20, in send_email
    sendemail(msg)
  File "/Users/main/PycharmProjects/microblog/app/email.py", line 37, in sendemail
    server = smtplib.SMTP("MAIL_SERVER")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
2021-08-30 20:16:55,690 INFO: Microblog startup [in /Users/main/PycharmProjects/microblog/app/__init__.py:54]
